name: ssl-vit-env
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.11
  - pip
  - pip:
      - torch==2.1.0
      - torchvision==0.16.0
      - torchaudio==2.1.0
      - matplotlib
      - numpy
      - scikit-learn
      - pandas
      - opencv-python
      - tqdm
      - seaborn
      - jupyter
      - notebook
